repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: fmt-check
        name: fmt-check
        entry: nix-shell --run 'just fmt-check'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: lint-typos
        name: lint-typos
        entry: nix-shell --run 'just lint-typos'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: lint-clippy
        name: lint-clippy
        entry: nix-shell --run 'just lint-clippy'
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: test
        name: test
        entry: nix-shell --run 'just test'
        language: system
        pass_filenames: false
        stages: [pre-push]
